---
title: "Untitled"
format: html

filters: 
    - include-code-files
---

## Challenge #1: Decode a string

Implement a function named `decode_string` that takes an encoded string and returns the decoded value (`hgiikf` is decoded to `butter`).

Hint: See the function definition in `secret_recipe_decoder.py`.

```{python}
import sys
import os
```

``` {.python include="secret_recipe_decoder.py"}
```

``` {.python include="test_secret_recipe_decoder.py"}
```

``` {.python include="main.py"}
```

``` {include="secret_recipe.txt"}
```

```{python}
%run "secret_recipe_decoder.py"
```

```{python}
%run "test_secret_recipe_decoder.py"
```

```{python}
decode_string("hgiikf")
```

# Challenge 2: Decode an Ingredient

Implement a function named decode_ingredient that takes a line from the recipe and returns a new Ingredient (a class already defined for you). The \# sign delimits the encoded amount and the description of an ingredient. For example, the line 8 vgl#hgiikf would return an Ingredient with an amount of 1 cup and a description of butter.

Hint: See the function definition inside the secret_recipe_decoder.py file

```{python}
ingredient = decode_ingredient("8 vgl#hgiikf")
print(ingredient.amount, ingredient.description)
```

## Challenge #3: Decode the entire recipe

In the `main` method, read all of the ingredients out of `secret_recipe.txt`, decode each ingredient (hopefully using the functions you implemented above), and save the output into a new file named `decoded_recipe.txt`.

```{python}
secret_recipe_decoder()
```

# Testing the project

You can run the tests by running the following:

```         
pytest
```